### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by lff5** [dev-lab/tmbus#1]
I stumbled upon a bug. Inside function `ba2i()` code can get infinitely stuck with invalid mbus frame.

Here is the function:
https://github.com/dev-lab/tmbus/blob/2e04a76622475b251797d1e3d7b613b532e14b19/tmbus.js#L106C9-L106C9
```
function ba2i(a) {
	var i = ln(a);
	if(i > 4) return a;
	var r = a[--i], m = i == 3 ? 0 : r&128 ? (r&=127, -(1<<i*8+7)) : 0;
	while(i) r = (r<<8) + a[--i];
	return r + m;
}
```

Variable `i` can initially be 0, since `ln()` can return 0 as seen below:
```
function ln(t) {
	return t ? t.length || 0 : 0;
}
```

Since `i--` occurs before `while(i)` loop, `i` would be negative when entering `while(i) i--;` causing infinite loop.

Solution:
I propose to use `while(i>0)` instead of just `while(i)`

**Comment by dev-lab** [comment]
If `i==0` at the beginning, the statement `r = a[-1]` makes r undefined, and that doesn't look good to me.
So, I have to check the M-Bus standard and review the algorithm, probably `while(i>0)` is not enough to fix it.

**Comment by lff5** [comment]
My bad, indeed `if (i==0)` at the beginning is the correct way.

I guess the M-Bus documentation doesn't say anything about it, because it only occurs with faulty frame.

Maybe call `er("Invalid length"); return smth;` when `i==0` so the error does not go unnoticed?

BTW I couldn't believe M-Bus spec can be implemented so compactly. Thats amazing!

**Comment by dev-lab** [comment]
Although throwing an exception looks better, the bug is fixed with returning 0 for blank input.
Compactness must go on! ;-)

Thank you for pointing out the bug and for the kind words about the library!
