### ISSUE TITLE
Typo in deVifB function

### ISSUE THREAD

**Issue by havrak** [dev-lab/tmbus#2]
Hello if noticed a error in deVifB function  in `b = (d >> --i) & 1  ? (ln(b) <= 1 ? O : b[1]) : b[0];` expression. Originally there is just ln(b) < 1 which will result in error since if ln(b) is equal to one element b[1] will not exists. It's just a small typo so I will not open a push request.

Hope this is clear no changes are required in any other place.

**Comment by dev-lab** [comment]
Yes, it's definitely a bug, thank you for reporting it.
