### ISSUE TITLE
Casting error

### ISSUE THREAD

**Issue by havrak** [dev-lab/tmbus#3]
Hello,

in function p10, variable `s` is sometimes interpreted as number (occurred to me with message 681B1B6808007263510722AC4809071F00000006132B00000000000F010101D016
),. Than calling `const b = (s ? s.charAt(0) == '-' : n < 0) ? 1 : 0;` will fail as `.charAt(0)` is not defined for numbers and will fail. I suggest either forcing .toString() or instead of comparing for minus sign just check if number is smaller than  0.  Though I have no idea why it fails with this message specifically and not others. 

Sincerely 

Havrak

**Comment by dev-lab** [comment]
Havrak,

Thanks again for taking the time to find bugs in the tmbus library.
Fixed it, and now your datagram is decoded as 0.043 m³ of water.

Taras.
