### ISSUE TITLE
Missing VIF scaling factor parsing

### ISSUE THREAD

**Issue by schiermi** [dev-lab/tmbus#4]
The scaling factor (part of the VIF) is currently not parsed.

In https://github.com/maebli/m-bus-parser/ (rust) it's implemented like this:
https://github.com/maebli/m-bus-parser/blob/afa0c514e322c6f011730081a2c782e401fc8cb6/src/user_data/value_information.rs#L181

I tried to identify where in https://github.com/dev-lab/tmbus/blob/main/tmbus.js this could be done, but it's hard for me to follow the code. Is there a more "verbose" (e.g. less shortened function names) version of this file available?

Example telegram to compare at https://dev-lab.github.io/tmbus/tmbus.htm & https://maebli.github.io/m-bus-parser/:
`68 78 78 68 08 00 72 09 70 26 18 52 3b 0e 02 3e 00 00 00 07 80 75 2d 5b d4 1a 1a 00 00 00 87 40 80 75 00 00 00 00 00 00 00 00 87 10 80 75 64 43 9e 1a 1a 00 00 00 87 50 80 75 00 00 00 00 00 00 00 00 87 20 80 75 c9 17 36 00 00 00 00 00 87 60 80 75 00 00 00 00 00 00 00 00 c7 00 29 f6 52 00 00 00 00 00 00 0d 78 0e 36 36 36 32 38 39 30 36 31 31 59 53 45 31 03 fd 17 80 00 01 45 16`

tmbus (wrong, 11211927 kWh):
```
 Storage 0
	Tariff 0
	Energy	11211927428.5 Wh
```

m-bus-parser (correct, 11211 kWh):
```
+-------------------------------------+------------------------+
| Value                               | Data Information       |
+=====================================+========================+
| (112119274285)e-4[Wh]               | 0,Inst,64-bit Integer  |
+-------------------------------------+------------------------+
```

**Comment by dev-lab** [comment]
Thank you for reporting the bug!
There is no "more verbose" version of tmbus library, but there is a [minified one](https://dev-lab.github.io/tmbus/tmbus.min.js). :-)
The reason of the bug was that the VIFE multiplicative correction factor was overwriting VIF scaling factor, while should be accumulated instead.

**Comment by schiermi** [comment]
I saw the minified one. I tried to wrap my head around the tmbus.js but together with my sparse mbus knowledge I failed to narrow it down on my own. Thanks a lot for the ultra-fast fix.
