### ISSUE TITLE
Power unit scale

### ISSUE THREAD

**Issue by adadevlabs** [dev-lab/tmbus#5]
Hi,

I noticed a weird result working with power units.

Using the following vif, dif and values: `040a40be4025`, the result should be `62.5GJ`, instead I have a `625 GJ`.

Searching through the code, I found this [array](https://github.com/dev-lab/tmbus/blob/main/tmbus.js#L409). Each second item of this array seems to be the lowest 10^n value for each units. 

Going through MBus standard documentation, we can see the following:
![image](https://github.com/user-attachments/assets/73e96096-443f-4ce5-a7ca-bb18a98dc017)
(c.f. page 78 of documentation)

Looks like this [item](https://github.com/dev-lab/tmbus/blob/main/tmbus.js#L410) and this [item](https://github.com/dev-lab/tmbus/blob/main/tmbus.js#L410) should have their second value set to `0` instead of `1`.

**Comment by dev-lab** [comment]
Adrien,

Thanks for the bug report.
Your assumptions are correct, there is an error in the power of ten calculation for both J and J/h.
The fix you suggested is right too, I have applied it.

Thanks,
Taras.
